# These are supported funding model platforms

github: [ajeetraina, openusm, collabnix, abendigeri]
patreon: collabnix
open_collective: collabnix
ko_fi: # http://ko-fi.com/K3K5AZX5
tidelift: npm/babel
community_bridge: # collabnix
custom: # http://ko-fi.com/K3K5AZX5
