apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
 affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: disktype
           operator: In
           values:
           - ssd
           - magnetic
         - key: role
           operator: NotIn
           values:
           - monitoring

 containers:
 - name: nginx
   image: nginx