version: '2'

services:
  a:
    image: alpine:3.6
    command: ping 127.0.0.1
    networks:
      - docknet
    volumes:
      - "nfsmount:#{CONTAINER_DIR}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]



networks:
  docknet:
    external: true


volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${SOURCE_DIR}"
